### ISSUE TITLE
Is FileSystemOptions class missing?

### ISSUE THREAD

**Issue by zamirov** [KristofferStrube/Blazor.FileSystemAccess#61]
After updating to 3.3.0 I get error
`error CS7069: Reference to type 'FileSystemOptions' claims it is defined in 'KristofferStrube.Blazor.FileSystem', but it could not be found`
I don't see it in the repo as well. How could it even build nuget?
